# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         actions/setup/action.jinja2.yml
#     Generated Date:         2022-11-08 14:24:15.754322
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-28 10:31:11
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Setup
description: Runs `Setup` or `Bootstrap` on the repository.

inputs:
  repo_name:                                {type: string, required: true}
  repo_dir:                                 {type: string, required: true}
  branch_overrides:                         {type: string, required: false}

  os:                                       {type: string, required: true}
  configuration:                            {type: string, required: true}

  local_script_prefix:                      {type: string, required: true}
  script_extension:                         {type: string, required: true}
  shell_name:                               {type: string, required: true}
  sudo_command:                             {type: string, required: true}
  working_dir:                              {type: string, required: true}

runs:
  using: composite
  steps:
    # BugBug: Clean this up

    - name: Setup (No Configuration)
      if: ${{ inputs.repo_name == 'davidbrownell/v4-Common_Foundation' && inputs.configuration == 'None' }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Setup${{ inputs.script_extension }} --no-interactive --no-hooks --debug
      shell: ${{ inputs.shell_name }}

    - name: Setup (with Configuration)
      if: ${{ inputs.repo_name == 'davidbrownell/v4-Common_Foundation' && inputs.configuration != 'None' }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Setup${{ inputs.script_extension }} --configuration ${{ inputs.configuration }} --no-interactive --no-hooks --debug
      shell: ${{ inputs.shell_name }}

    # Do not let repositories in the '_actions' directory be used as dependency repositories during the bootstrap process
    # (as the fall outside the `all_repositories_root` directory and are therefore not setup).

    # There are probably shell scripts to do this cleaning, but it feels easier to do the work in python
    - name: Generate Clean Actions (ubuntu)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && startsWith(inputs.os, 'ubuntu') }}
      run: |
          cat > _clean_action_dir.py <<EOF
          import os
          from pathlib import Path

          for parent in Path.cwd().parents:
            potential_folder = parent / '_actions'
            if potential_folder.is_dir():
              for root, _, filenames in os.walk(potential_folder):
                for filename in filenames:
                  if filename == '__RepositoryId__':
                    fullpath = Path(root) / filename
                    print(fullpath)

                    fullpath.unlink()

              break
          EOF
      shell: bash

    - name: Generate Clean Actions (windows)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && startsWith(inputs.os, 'windows') }}
      run: |
        $python_content = @"
        import os
        from pathlib import Path

        for parent in Path.cwd().parents:
          potential_folder = parent / '_actions'
          if potential_folder.is_dir():
            for root, _, filenames in os.walk(potential_folder):
              for filename in filenames:
                if filename == '__RepositoryId__':
                  fullpath = Path(root) / filename
                  print(fullpath)

                  fullpath.unlink()

            break
        "@

        Add-Content "_clean_action_dir.py" $python_content
      shell: powershell

    - name: Clean Actions
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' }}
      run: |
        python _clean_action_dir.py
        python -c "import os; os.remove('_clean_action_dir.py')"
      shell: ${{ inputs.shell_name }}

    # BugBug: Remove branch name in all of these
    # BugBug: Simplify this code if there is a ternary operator available

    - name: Bootstrap (No Configuration)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && inputs.configuration == 'None' && !inputs.branch_overrides }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} ${{ inputs.working_dir }}/code --no-interactive --no-hooks --debug --branch davidbrownell_release
      shell: ${{ inputs.shell_name }}

    - name: Bootstrap (with Configuration)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && inputs.configuration != 'None' && !inputs.branch_overrides }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} ${{ inputs.working_dir }}/code --configuration ${{ inputs.configuration }} --no-interactive --no-hooks --debug --branch davidbrownell_release
      shell: ${{ inputs.shell_name }}

    - name: Bootstrap (No Configuration, with Branch Overrides)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && inputs.configuration == 'None' && inputs.branch_overrides }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} ${{ inputs.working_dir }}/code --no-interactive --no-hooks --debug --branch davidbrownell_release --branch-overrides "${{ inputs.branch_overrides }}"
      shell: ${{ inputs.shell_name }}

    - name: Bootstrap (with Configuration, with Branch Overrides)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && inputs.configuration != 'None' && inputs.branch_overrides }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} ${{ inputs.working_dir }}/code --configuration ${{ inputs.configuration }} --no-interactive --no-hooks --debug --branch davidbrownell_release --branch-overrides "${{ inputs.branch_overrides }}"
      shell: ${{ inputs.shell_name }}
