# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         actions/setup/action.jinja2.yml
#     Generated Date:         2022-11-08 16:07:39.589863
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-28 10:31:11
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Setup
description: Runs `Setup` or `Bootstrap` on the repository.

inputs:
  repo_name:                                {type: string, required: true}
  repo_dir:                                 {type: string, required: true}
  branch_overrides:                         {type: string, required: false}

  os:                                       {type: string, required: true}
  configuration:                            {type: string, required: true}

  local_script_prefix:                      {type: string, required: true}
  script_extension:                         {type: string, required: true}
  shell_name:                               {type: string, required: true}
  sudo_command:                             {type: string, required: true}
  working_dir:                              {type: string, required: true}

runs:
  using: composite
  steps:
    # Do not let repositories in the '_actions' directory be used as dependency repositories during the bootstrap process
    # (as the fall outside the `all_repositories_root` directory and are therefore not setup).

    # There are probably shell scripts to do this cleaning, but it feels easier to do the work in python
    - name: Generate Clean Actions (ubuntu)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && startsWith(inputs.os, 'ubuntu') }}
      run: |
          cat > _clean_action_dir.py <<EOF
          import os
          from pathlib import Path

          for parent in Path.cwd().parents:
            potential_folder = parent / '_actions'
            if potential_folder.is_dir():
              for root, _, filenames in os.walk(potential_folder):
                for filename in filenames:
                  if filename == '__RepositoryId__':
                    fullpath = Path(root) / filename
                    print(fullpath)

                    fullpath.unlink()

              break
          EOF
      shell: bash

    - name: Generate Clean Actions (windows)
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' && startsWith(inputs.os, 'windows') }}
      run: |
        $python_content = @"
        import os
        from pathlib import Path

        for parent in Path.cwd().parents:
          potential_folder = parent / '_actions'
          if potential_folder.is_dir():
            for root, _, filenames in os.walk(potential_folder):
              for filename in filenames:
                if filename == '__RepositoryId__':
                  fullpath = Path(root) / filename
                  print(fullpath)

                  fullpath.unlink()

            break
        "@

        Add-Content "_clean_action_dir.py" $python_content
      shell: powershell

    - name: Clean Actions
      if: ${{ inputs.repo_name != 'davidbrownell/v4-Common_Foundation' }}
      run: |
        python _clean_action_dir.py
        python -c "import os; os.remove('_clean_action_dir.py')"
      shell: ${{ inputs.shell_name }}

    - name: Setup Statement
      id: setup_statement
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var setup_statement;

          if("${{ inputs.repo_name }}" == "davidbrownell/v4-Common_Foundation") {
            setup_statement = "${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Setup${{ inputs.script_extension }}";
          } else {
            var path = require("path");

            setup_statement = "${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} \"" + path.join("${{ inputs.working_dir }}", "code") + "\"";

            if("${{ inputs.branch_overrides }}" != "") {
              setup_statement += " --branch-overrides \"${{ inputs.branch_overrides }}\"";
            }
          }

          setup_statement += " --no-interactive --no-hooks --debug";

          if("${{ inputs.configuration }}" != "None") {
            setup_statement += " --configuration \"${{ inputs.configuration }}\"";
          }

          return setup_statement;

    - name: Results
      shell: ${{ inputs.shell_name }}
      run: |
        echo "Setup Statement: ${{ steps.setup_statement.outputs.result }}"

    - name: Execute Setup Statement
      shell: ${{ inputs.shell_name }}
      run: |
        pushd "${{ inputs.repo_dir }}"
        ${{ steps.setup_statement.outputs.result }}
