# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-28 10:31:11
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Setup
description: Runs `Setup` or `Bootstrap` on the repository.

inputs:
  repo_name:                                {type: string, required: true}
  repo_dir:                                 {type: string, required: true}
  repo_dependencies_dir:                    {type: string, required: true}

  branch_overrides:                         {type: string, required: false}

  configuration:                            {type: string, required: true}

  local_script_prefix:                      {type: string, required: true}
  script_extension:                         {type: string, required: true}
  shell_name:                               {type: string, required: true}
  sudo_command:                             {type: string, required: true}

  force:                                    {type: boolean, required: false, default: false}

runs:
  using: composite
  steps:
    - name: Setup Statement
      id: setup_statement
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var setup_statement = "pushd \"" + String.raw`${{ inputs.repo_dir }}` + "\" && ";

          if("${{ inputs.repo_name }}" === "davidbrownell/v4-Common_Foundation") {

            // Handle the case where the repo under test is v4-Common_Foundation and the request is for
            // a branch/tag. In all other cases, this scenario is handled by Bootstrap/Enlist.
            if("${{ inputs.branch_overrides }}" !== "") {
              // In this scenario, the repo will be associated with the 'main_stable' branch. Switch
              // to the desired branch since this repo is the repo under test.
              var elements;

              elements = "${{ inputs.branch_overrides }}".split(";");
              console.assert(elements.length === 1, "%o", {elements});

              elements = elements[0].split(":");
              console.assert(elements.length === 2, "%o", {elements});
              console.assert(elements[0] === "Common_Foundation", "%o", {elements});

              setup_statement += `git checkout "${elements[1]}" && `;
            }

            setup_statement += "${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Setup${{ inputs.script_extension }}";
          } else {
            var path = require("path");

            setup_statement += "${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} \"" + String.raw`${{ inputs.repo_dependencies_dir }}` + "\"";

            if("${{ inputs.branch_overrides }}" !== "") {
              setup_statement += " --branch-overrides \"${{ inputs.branch_overrides }}\"";
            }
          }

          setup_statement += " --no-interactive --no-hooks --debug";

          if("${{ inputs.force }}".toLowerCase() === "true")
            setup_statement += " --force";

          if("${{ inputs.configuration }}" !== "None") {
            setup_statement += " --configuration \"${{ inputs.configuration }}\"";
          }

          return setup_statement;

    - name: Results
      shell: ${{ inputs.shell_name }}
      run: |
        echo "Setup Statement: ${{ steps.setup_statement.outputs.result }}"

    - name: Setup
      shell: ${{ inputs.shell_name }}
      run: ${{ steps.setup_statement.outputs.result }}
