# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-28 10:31:11
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Setup
description: Runs `Setup` or `Bootstrap` on the repository.

inputs:
  repo_name:                                {type: string, required: true}
  repo_dir:                                 {type: string, required: true}
  repo_dependencies_dir:                    {type: string, required: true}

  branch_overrides:                         {type: string, required: false}

  configuration:                            {type: string, required: true}

  local_script_prefix:                      {type: string, required: true}
  script_extension:                         {type: string, required: true}
  shell_name:                               {type: string, required: true}
  sudo_command:                             {type: string, required: true}

  force:                                    {type: boolean, required: false, default: false}

runs:
  using: composite
  steps:
    - name: Setup Statement
      id: setup_statement
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var bootstrap_statement = "pushd \"" + String.raw`${{ inputs.repo_dir }}` + "\" && ";
          var forced_foundation_branch = false;

          if("${{ inputs.repo_name }}".endsWith("Common_Foundation") && "${{ inputs.branch_overrides }}" !== "") {
            forced_foundation_branch = true;

            // Checkout the specified branch
            var elements;

            elements = "${{ inputs.branch_overrides }}".split(";");
            console.assert(elements.length === 1, "%o", {elements});

            elements = elements[0].split(":");
            console.assert(elements.length === 2, "%o", {elements});
            console.assert(elements[0] === "Common_Foundation", "%o", {elements});

            bootstrap_statement += `git checkout "${elements[1]}" && `;
          }

          bootstrap_statement += "${{ inputs.sudo_command }}${{ inputs.local_script_prefix }}Bootstrap${{ inputs.script_extension }} \"" + String.raw`${{ inputs.repo_dependencies_dir }}` + "\"";

          if("${{ inputs.branch_overrides }}" !== "" && !forced_foundation_branch)
              bootstrap_statement += " --branch-overrides \"${{ inputs.branch_overrides }}\"";

          bootstrap_statement += " --no-interactive --no-hooks --debug";

          if("${{ inputs.force }}".toLowerCase() === "true")
            bootstrap_statement += " --force";

          if("${{ inputs.configuration }}" !== "None") {
            bootstrap_statement += " --configuration \"${{ inputs.configuration }}\"";
          }

          return bootstrap_statement;

    - name: Results
      shell: ${{ inputs.shell_name }}
      run: |
        echo "Setup Statement: ${{ steps.setup_statement.outputs.result }}"

    - name: Setup
      shell: ${{ inputs.shell_name }}
      run: ${{ steps.setup_statement.outputs.result }}
