<<#
# ----------------------------------------------------------------------
# |
# |  _PersistEnvironmentVars.macro.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 10:34:55
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
#>>

<<% macro Execute(environment_vars) -%>>
      run: |
        python -c "import os; f = open(os.getenv('GITHUB_OUTPUT'), 'a+'); f.write('<<< environment_vars | format_and_reduce("{}={{}}\\n", "") >>>'.format(<<< environment_vars | format_and_reduce("os.getenv('_{}')", ", ") >>>)); f.close();"
        python -c "import os; f = open(os.getenv('GITHUB_ENV'), 'a+'); f.write('<<< environment_vars | format_and_reduce("_{}=\\n", "") >>>'); f.close();"
<<%- endmacro %>>
