# ----------------------------------------------------------------------
# |
# |  callable_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:08:27
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
<<% extends "../_BuildAndTest.template.yaml" %>>

<<% block name %>>"[impl] Common_Foundation-based Repository Validation"<<% endblock %>>
