# ----------------------------------------------------------------------
# |
# |  callable_create_stable_tag.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 13:48:26
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
on:
  workflow_call:
    inputs:
      branch:                               {type: string, required: true}
      commit:                               {type: string, required: true}

jobs:
  _c29f4dc3-f949-4b4f-b4c4-16d3a63aad1c:
    name: "Create 'stable' tag on '${{ inputs.branch }}'"
    runs-on: ubuntu-latest

    steps:
      - name: "[Impl] Dump Contexts"
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-v1.2.0

      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ inputs.branch }}

      - name: Create Tag
        shell: bash
        run: |
          git config user.name "Github Action Bot"
          git config user.email "<>"

          git tag --annotate --force -m "🤖 Stability Verified" "${{ inputs.branch }}_stable" ${{ inputs.commit }}
          git push origin "${{ inputs.branch }}_stable" --force
