# ----------------------------------------------------------------------
# |
# |  callable_release.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 13:48:26
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
on:
  workflow_call:
    inputs:
      source_branch:
        type: string
        required: true
        description: BugBug1

      dest_branch:
        type: string
        required: true
        description: BugBug2

jobs:
  ReleaseJob:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          ref: refs/heads/${{ inputs.source_branch }}

      - name: Create Pull Request
        run: gh pr create -B ${{ inputs.dest_branch }} -H ${{ inputs.source_branch }} --title 'Merge "${{ inputs.source_branch }}" into "${{ inputs.dest_branch }}"' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
