# ----------------------------------------------------------------------
# |
# |  callable_commit_integrity_checks.jinja2.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-03-03 09:28:09
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
<<% extends "../_CommitIntegrityChecks.template.yaml" %>>

<<% block cic_name %>>"[impl] Common_Foundation-based Repository Commit Integrity Checks"<<% endblock %>>
