# ----------------------------------------------------------------------
# |
# |  callable_pr_to_main.jinja2.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-08 12:52:02
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
on:
  workflow_call:

jobs:
  Workflow:
    uses: ./.github/workflows/exercise_main.yaml
