# ----------------------------------------------------------------------
# |
# |  event_periodic.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:09:24
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on periodic"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 0 * * *' # Once a day at 12am UTC

jobs:
  _b0665d98-3e6b-41d7-85ec-41f2eeb0ceee:
    name: "Validate (${{ github.ref_name }})"
    if: ${{ github.repository == 'davidbrownell/v4-Common_Foundation' }}
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: ${{ github.ref_name }}

  _eb3cc2cb-2aaa-457a-894b-a555ae025e78:
    name: "Validate with Dependencies (${{ github.ref_name }})"
    if: ${{ github.repository == 'davidbrownell/v4-Common_Foundation' }}
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate_with_dependencies.yaml@CI-v1
    with:
      repo_branch: ${{ github.ref_name }}

    needs:
      - _b0665d98-3e6b-41d7-85ec-41f2eeb0ceee

  _a7d72ec5-5504-4c89-a8a3-b122097e2870:
    name: Status Message
    if: ${{ github.repository != 'davidbrownell/v4-Common_Foundation' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will only run on 'davidbrownell/v4-Common_Foundation'." }}
