# ----------------------------------------------------------------------
# |
# |  event_on_push.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:09:01
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on push"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  _0166baf5-0ecf-4262-b29a-526c500f6d06:
    name: "Validate"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}

  _efaeb2d9-1508-4304-b3e7-ca2cd6377ff5:
    name: "Promote"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_promote.yaml@CI-latest

    needs:
      - _0166baf5-0ecf-4262-b29a-526c500f6d06
