# ----------------------------------------------------------------------
# |
# |  event_periodic.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:09:24
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on periodic"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 9 * * *' # Once a day at 9am UTC
  workflow_dispatch:

jobs:
  _b0665d98-3e6b-41d7-85ec-41f2eeb0ceee:
    name: "Validate"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate.yaml@CI-latest
