# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:08:44
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: "${{ github.run_number }} [${{ github.actor }}] ${{ github.head_ref }} -> ${{ github.base_ref }}"

on:
  pull_request:
    branches:
      - main

jobs:
  _5b21e650-3435-4467-961e-1f0cacd31dcb:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate.yaml@CI-v1
    with:
      repo_branch: ${{ github.head_ref }}

  _6009b681-9a5b-4952-8914-8bb7ce927b82:
    name: "Validate Pull Request (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate_pull_request.yaml@CI-v1
    with:
      job_name_prefix: Common_Foundation
      repo_name: davidbrownell/v4-Common_Foundation
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: python310
