# ----------------------------------------------------------------------
# |
# |  exercise_main-Impl.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 13:54:33
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
<<% extends "../_BuildAndTest.template.yaml" %>>
