# ----------------------------------------------------------------------
# |
# |  manual_validate_with_dependencies.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:07:47
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate (including dependencies)"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _0af7f16a-58ea-4d13-8906-fa6f7cd60944:
    name: "Validate"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate_with_dependencies.yaml@CI-latest
    with:
      repo_branch:                          ${{ github.ref_name }}
