# ----------------------------------------------------------------------
# |
# |  manual_validate.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:07:27
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "Validate"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  _f4dfba31-0393-4d24-b807-b4fcf0703a5c:
    name: "Build and Test (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_validate.yaml@CI-latest
