# ----------------------------------------------------------------------
# |
# |  on_push_to_main.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 13:35:13
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: OnPush (main)
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }} # BugBug: Change this

on:
  push:
    branches:
      - main
      - davidbrownell_main # BugBug
  workflow_dispatch:

jobs:
  Common_Foundation:
    uses: ./.github/workflows/exercise_main.yaml
    with:
      setup_branch_overrides: "Common_Foundation:${{ github.base_ref }}"
      subject_repo_name: "davidbrownell/v4-Common_Foundation"

  Common_PythonDevelopment:
    uses: davidbrownell/v4-Common_PythonDevelopment/.github/workflows/exercise_main.yaml@CI-vBugBug
    with:
      setup_branch_overrides: "Common_Foundation:${{ github.base_ref }}"
      subject_repo_name: "davidbrownell/v4-Common_PythonDevelopment"
      subject_repo_branch: davidbrownell_main # BugBug

  # ----------------------------------------------------------------------
  Promote:
    name: "Promote (Common_Foundation)"

    needs:
      - Common_Foundation
      - Common_PythonDevelopment

    uses: ./.github/workflows/callable_promote_to_release.yaml
    with:
      # BugBug dest_branch: release

      source_branch: ${{ github.base_ref }}
      dest_branch: davidbrownell_release # BugBug: We should be able to get this
