# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         actions/dump_contexts/action.jinja2.yml
#     Generated Date:         2022-11-17
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 22:10:25
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Dump GitHub Action Contexts
description: Dumps different contexts.

# For these steps, I want to print the json content. Unfortunately, I haven't been able to figure out
# a way to escape characters required to display the json content (for example, "echo '${{ toJson(...) }}'
# runs into problems when the json content contains "'" chars.
#
# What follows feels like a MASSIVE hack.

runs:
  using: composite
  steps:
    - name: Dump github Context
      shell: bash
      run: |
        set +e

        echo "github:"
        echo ""

        cat > _github_context <<EOL
        ${{ toJSON(github) }}
        EOL

        cat _github_context

        exit 0

    - name: Dump job Context
      shell: bash
      run: |
        set +e

        echo "job:"
        echo ""

        cat > _job_context <<EOL
        ${{ toJSON(job) }}
        EOL

        cat _job_context

        exit 0

    - name: Dump steps Context
      shell: bash
      run: |
        set +e

        echo "steps:"
        echo ""

        cat > _steps_context <<EOL
        ${{ toJSON(steps) }}
        EOL

        cat _steps_context

        exit 0

    - name: Dump runner Context
      shell: bash
      run: |
        set +e

        echo "runner:"
        echo ""

        cat > _runner_context <<EOL
        ${{ toJSON(runner) }}
        EOL

        cat _runner_context

        exit 0

    - name: Dump strategy Context
      shell: bash
      run: |
        set +e

        echo "strategy:"
        echo ""

        cat > _strategy_context <<EOL
        ${{ toJSON(strategy) }}
        EOL

        cat _strategy_context

        exit 0

    - name: Dump matrix Context
      shell: bash
      run: |
        set +e

        echo "matrix:"
        echo ""

        cat > _matrix_context <<EOL
        ${{ toJSON(matrix) }}
        EOL

        cat _matrix_context

        exit 0

