@echo off
SET DEVELOPMENT_ENVIRONMENT_ENVIRONMENT_NAME=DefaultEnv
pushd "%~dp0"
call "C:\Code\v4\Common\Foundation\RepositoryBootstrap\Impl\Activate.cmd" %*
set _DEVELOPMENT_ENVIRONMENT_ACTIVATE_ERROR=%ERRORLEVEL%
popd
if %_DEVELOPMENT_ENVIRONMENT_ACTIVATE_ERROR% NEQ 0 (exit /B %_DEVELOPMENT_ENVIRONMENT_ACTIVATE_ERROR%)