# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2023-03-03 13:45:38
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2023
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Pull Request Validator
description: Validates Pull Requests.

inputs:
  shell_name:                               {type: string, required: true}
  script_extension:                         {type: string, required: true}

  activate_statement:                       {type: string, required: true}

  destination_branch:                       {type: string, required: true}

runs:
  using: composite
  steps:
    - name: "Validate Pull Request"
      shell: "${{ inputs.shell_name }}"
      run: |
        ${{ inputs.activate_statement }} && PullRequestValidator${{ inputs.script_extension }} Validate "origin/${{ inputs.destination_branch }}" --debug
