# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-31 11:22:35
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Initialize
description: Initializes OS-Specific Variables used by other composable actions.

inputs:
  os:                                       {type: string, required: true}

outputs:
  github_workspace:
    description: "The GITHUB_WORKSPACE environment variable."
    value: ${{ steps.github_workspace.outputs.result }}

  local_script_prefix:
    description: "Prefix used when invoking a script in the current directory."
    value: ${{ steps.local_script_prefix.outputs.result }}

  script_extension:
    description: "File extension used for scripts."
    value: ${{ steps.script_extension.outputs.result }}

  shell_name:
    description: "Name of shell used to invoke GitHub actions."
    value: ${{ steps.shell_name.outputs.result }}

  source_command:
    description: "Command used when invoking a script that changes the state of the current environment."
    value: ${{ steps.source_command.outputs.result }}

  sudo_command:
    description: "Command used to invoke privileged operations."
    value: ${{ steps.sudo_command.outputs.result }}

runs:
  using: composite
  steps:
<<%
  set values = [
    ("Github Workspace", "github_workspace", "process.env.GITHUB_WORKSPACE", "process.env.GITHUB_WORKSPACE"),
    ("Local Script Prefix", "local_script_prefix", '""', '"./"'),
    ("Script Extension", "script_extension", '".cmd"', '".sh"'),
    ("Shell Name", "shell_name", '"cmd"', '"bash"'),
    ("Source Command", "source_command", '""', '". "'),
    ("Sudo Command", "sudo_command", '""', '"sudo "'),
  ]
%>>
<<% for name, id, windows_value, linux_value in values %>>

    - name: <<< name >>>
      id: <<< id >>>
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          return "${{ inputs.os }}".startsWith("windows") ? <<< windows_value >>> : <<< linux_value >>>;
<<% endfor %>>

    - name: Results
      shell: ${{ steps.shell_name.outputs.result }}
      run: |
<<% for name, id, windows_value, linux_value in values %>>
        echo "<<< name >>>: '${{ steps.<<< id >>>.outputs.result }}'"
<<% endfor %>>
