# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-31 11:22:35
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Initialize
description: Initializes OS-Specific Variables used by other composable actions.

inputs:
  os:                                       {type: string, required: true}

outputs:
  local_script_prefix:
    description: "Prefix used when invoking a script in the current directory."
    value: ${{ steps.local_script_prefix.outputs.result }}

  script_extension:
    description: "File extension used for scripts."
    value: ${{ steps.script_extension.outputs.result }}

  shell_name:
    description: "Name of shell used to invoke GitHub actions."
    value: ${{ steps.shell_name.outputs.result }}

  source_command:
    description: "Command used when invoking a script that changes the state of the current environment."
    value: ${{ steps.source_command.outputs.result }}

  sudo_command:
    description: "Common used to invoke privileged operations."
    value: ${{ steps.sudo_command.outputs.result }}

  working_dir:
    description: "Working directory."
    value: ${{ steps.working_directory.outputs.result }}

runs:
  using: composite
  steps:
    <<%
      set values = [
        ("Local Script Prefix", "local_script_prefix", '""', '"./"'),
        ("Script Extension", "script_extension", '".cmd"', '".sh"'),
        ("Shell Name", "shell_name", '"cmd"', '"bash"'),
        ("Source Command", "source_command", '""', '". "'),
        ("Sudo Command", "sudo_command", '""', '"sudo "'),
        ("Working Directory", "working_directory", "process.env.RUNNER_TEMP", "process.env.RUNNER_TEMP"),
      ]
    %>>
    <<% for name, id, windows_value, linux_value in values %>>
    - name: <<< name >>>
      id: <<< id >>>
      uses: actions/github-script@v6
      with:
        script: |
          return "${{ inputs.os }}".startsWith("windows") ? <<< windows_value >>> : <<< linux_value >>>;
        result-encoding: string

    <<% endfor %>>
