# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         actions/checkout_source/action.jinja2.yml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 16:19:23
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Checkout Source
description: Checks out source code.

inputs:
  repo_name:                                {type: string, required: true}
  repo_branch:                              {type: string, required: false}

  os:                                       {type: string, required: true}
  configuration:                            {type: string, required: true}

  shell_name:                               {type: string, required: true}

outputs:
  archive_prefix:
    description: "Prefix that can be applied to archive names to prevent collisions."
    value: ${{ steps.archive_prefix.outputs.result }}

  repo_dir:
    description: "Directory to the repository under build."
    value: ${{ steps.repo_dir.outputs.result }}

  repo_dependencies_dir:
    description: "Directory to the repositories dependencies."
    value: ${{ steps.repo_dependencies_dir.outputs.result }}

runs:
  using: composite
  steps:

    - name: Archive Prefix
      id: archive_prefix
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var source_repo_name = "${{ inputs.repo_name }}".split("/", 2)[1];

          return "[${{ github.run_number }}, " + source_repo_name + ", ${{ inputs.os }}, ${{ inputs.configuration }}]"

    - name: Repo Directory
      id: repo_dir
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var path = require("path");

          return path.join(process.env.GITHUB_WORKSPACE, "repo_under_test");

    - name: Repo Dependencies Directory
      id: repo_dependencies_dir
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var path = require("path");

          return path.join(process.env.GITHUB_WORKSPACE, "repo_dependencies");

    - name: Results
      shell: ${{ steps.shell_name.outputs.result }}
      run: |
        echo "Archive Prefix: '${{ steps.archive_prefix.outputs.result }}'"
        echo "Repo Directory: '${{ steps.repo_dir.outputs.result }}'"
        echo "Repo Dependencies Directory: '${{ steps.repo_dependencies_dir.outputs.result }}'"

    - name: Checkout Source (Custom Repo)
      shell: ${{ inputs.shell_name }}
      run: |
        git clone --branch ${{ inputs.repo_branch || 'main_stable' }} https://github.com/${{ inputs.repo_name }} "${{ steps.repo_dir.outputs.result }}"
