# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-07 22:10:25
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Dump GitHub Action Contexts
description: Dumps different contexts.

# For these steps, I want to print the json content. Unfortunately, I haven't been able to figure out
# a way to escape characters required to display the json content (for example, "echo '${{ toJson(...) }}'
# runs into problems when the json content contains "'" chars.
#
# What follows feels like a MASSIVE hack.

runs:
  using: composite
  steps:
<<%
  set contexts = [
    "github",
    "job",
    "steps",
    "runner",
    "strategy",
    "matrix",
  ]
%>>
<<% for context in contexts %>>
    - name: Dump <<< context >>> Context
      shell: bash
      run: |
        echo "<<< context >>>:"
        echo ""

        cat > _<<< context >>>_context <<EOL
        ${{ toJSON(<<< context >>>) }}
        EOL

        cat _<<< context >>>_context

<<% endfor %>>
