name: "OnPush (main)"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  push:
    branches:
      - davidbrownell_relese
  workflow_dispatch:



jobs:
  BugBug:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "BugBug"
        shell: bash
