name: "OnPR 0.0.2"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - davidbrownell_release
      - 'davidbrownell_release/**'
      - 'davidbrownell_release/'
      - refs/heads/davidbrownell_release
      - 'refs/heads/davidbrownell_release/'
      - 'refs/heads/davidbrownell_release/**'
  workflow_dispatch:



jobs:
  BugBug:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "BugBug"
        shell: bash
