# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/callable_pr_to_release.jinja2.yaml
#     Generated Date:         2022-11-08 12:05:20.195382
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  callable_pr_to_release.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-08 11:33:24
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: callable_pr_to_release

on:
  workflow_call:

jobs:
  Workflow:
    name: Standard
    runs-on: ubuntu-latest

    steps:
      - name: "[Impl] Dump Contexts"
        uses: davidbrownell/v4-Common_Foundation/.github/actions/dump_contexts@CI-vBugBug

      - name: Verify User
        shell: bash
        run: |
          if [[ "${{ github.event.pull_request.user.login }}" == "github-actions[bot]" ]]; then
            exit 0
          fi

          echo "Pull requests to the branch '${{ github.base_ref }}' should only be initiated by the CI machine ('${{ github.event.pull_request.user.login }}' was found)."
          exit -1
