# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/event_on_pr.jinja2.yaml
#     Generated Date:         2022-11-18
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:08:44
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main

jobs:
  _5b21e650-3435-4467-961e-1f0cacd31dcb:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate.yaml@CI-latest
