# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/event_periodic.jinja2.yaml
#     Generated Date:         2022-11-17
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  event_periodic.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:09:24
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "periodic"
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  schedule:
    - cron: '0 9 * * *' # Once a day at 9am UTC
  workflow_dispatch: # BugBug

jobs:
  _b0665d98-3e6b-41d7-85ec-41f2eeb0ceee:
    name: "Build and Test (${{ github.ref_name }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/exercise.yaml@CI-latest
