# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
#
# This file is the result of a code generation process; any changes made
# to this file will be overwritten during the next code generation
# invocation. Any changes MUST be made in the source file rather than in
# this one.
#
#     Code Generator:         Jinja2
#     Input Filename:         workflows/event_on_pr.jinja2.yaml
#
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------
# ----------------------------------------------------------------------

# ----------------------------------------------------------------------
# |
# |  event_on_pr.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-11-17 08:08:44
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022-23
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: "on pull request"
run-name: "${{ github.run_number }} [${{ github.actor }}] ${{ github.head_ref }} -> ${{ github.base_ref }}"

on:
  pull_request:
    branches:
      - main

jobs:
  _5b21e650-3435-4467-961e-1f0cacd31dcb:
    name: "Validate (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/validate.yaml@CI-latest
    with:
      repo_branch: ${{ github.head_ref }}

  _6009b681-9a5b-4952-8914-8bb7ce927b82:
    name: "Commit Integrity Checks (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/callable_commit_integrity_checks.yaml@CI-BugBug
    with:
      job_name_prefix: Common_Foundation
      repo_name: davidbrownell/v4-Common_Foundation
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: python310

  _e9a77f26-073d-466e-b8a8-bb74baa04247:
    name: "Commit Integrity Checks [Common_Foundation] (target: ${{ github.base_ref }})"
    uses: davidbrownell/v4-Common_Foundation/.github/workflows/_common_foundation_commit_integrity_checks.yaml@CI-BugBug
    with:
      job_name_prefix: Common_Foundation
      repo_name: davidbrownell/v4-Common_Foundation
      repo_branch: ${{ github.head_ref }}
      os: ubuntu-latest
      configuration: python310
