# ----------------------------------------------------------------------
# |
# |  main.yaml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-27 13:55:11
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: main
run-name: ${{ github.run_number }} [${{ github.actor }}] on ${{ github.ref_name }}

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build_and_Test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        configuration:
          - python310
          # - python310_nolibs

        include:
          - local_dir:        ./
            os:               ubuntu-latest
            output_dir:       /tmp
            script_extension: .sh
            shell_name:       bash
            source_command:   ". "
            sudo:             "sudo "

          - local_dir:        ""
            os:               windows-latest
            output_dir:       "C:/Temp"
            script_extension: .cmd
            shell_name:       cmd
            source_command:   ""
            sudo:             ""

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: ./.github/actions/build_and_test
        with:
          configuration:    ${{ matrix.configuration }}
          local_dir:        ${{ matrix.local_dir }}
          os:               ${{ matrix.os }}
          output_dir:       ${{ matrix.output_dir }}
          script_extension: ${{ matrix.script_extension }}
          shell_name:       ${{ matrix.shell_name }}
          source_command:   ${{ matrix.source_command }}
          sudo:             ${{ matrix.sudo }}
