# ----------------------------------------------------------------------
# |
# |  action.yml
# |
# |  David Brownell <db@DavidBrownell.com>
# |      2022-10-28 10:56:24
# |
# ----------------------------------------------------------------------
# |
# |  Copyright David Brownell 2022
# |  Distributed under the Boost Software License, Version 1.0. See
# |  accompanying file LICENSE_1_0.txt or copy at
# |  http://www.boost.org/LICENSE_1_0.txt.
# |
# ----------------------------------------------------------------------
name: Activate
description: Runs `Activate` on the repository.

inputs:
  repo_dir:                                 {type: string, required: true}
  os:                                       {type: string, required: true}
  configuration:                            {type: string, required: true}
  shell_name:                               {type: string, required: true}

outputs:
  activate_statement:
    description: The command to activate the environment that can be used by other composite actions.
    value: ${{ steps.activate_statement.outputs.result }}

runs:
  using: composite
  steps:
    - name: Activate Statement
      id: activate_statement
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          var activate_statement;

          if("${{ inputs.os }}".startsWith("windows")) {
            console.log("BugBug1 " + "${{ inputs.repo_dir }}");
            console.log("BugBug2 " + "${{ inputs.repo_dir }}".replaceAll("\\", "\\\\"));

            activate_statement = "pushd \"" + "${{ inputs.repo_dir }}".replaceAll("\\", "\\\\") + "\" && Activate.cmd";
          } else {
            activate_statement = "pushd \"${{ inputs.repo_dir }}\" >> /dev/null && . ./Activate.sh";
          }

          if("${{ inputs.configuration }}" != "None") {
            activate_statement += " ${{ inputs.configuration }}";
          }

          activate_statement += " --debug";

          return activate_statement;

    - name: Results
      shell: ${{ inputs.shell_name }}
      run: |
        echo "Activate Statement: ${{ steps.activate_statement.outputs.result }}"

    - name: Activate
      shell: ${{ inputs.shell_name }}
      run: ${{ steps.activate_statement.outputs.result }}
